create extension if not exists pg_cron with schema extensions;

create table if not exists public.app_logs (
  id bigint generated by default as identity primary key,
  level text not null check (level in ('info', 'warn', 'error')),
  source text not null,
  message text not null,
  path text,
  user_id uuid references auth.users (id) on delete set null,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create index if not exists idx_app_logs_created_at on public.app_logs (created_at desc);
create index if not exists idx_app_logs_level_created_at on public.app_logs (level, created_at desc);
create index if not exists idx_app_logs_source on public.app_logs (source);

alter table public.app_logs enable row level security;

drop policy if exists "Admins can view app logs" on public.app_logs;

create policy "Admins can view app logs"
on public.app_logs
for select
using (
  exists (
    select 1
    from public.profiles
    where profiles.id = auth.uid()
      and profiles.role = 'admin'
      and profiles.is_deleted = false
  )
);

create or replace function public.cleanup_app_logs(retention interval default interval '30 days')
returns integer
language plpgsql
security definer
set search_path = public, pg_catalog
as $$
declare
  deleted_count integer := 0;
begin
  delete from public.app_logs
  where created_at < now() - retention;

  get diagnostics deleted_count = row_count;

  return deleted_count;
end;
$$;

revoke all on function public.cleanup_app_logs(interval) from public;
grant execute on function public.cleanup_app_logs(interval) to service_role;

do $$
declare
  existing_job_id bigint;
begin
  select jobid into existing_job_id
  from cron.job
  where jobname = 'cleanup_app_logs_daily';

  if existing_job_id is not null then
    perform cron.unschedule(existing_job_id);
  end if;

  perform cron.schedule(
    'cleanup_app_logs_daily',
    '17 3 * * *',
    $cron$select public.cleanup_app_logs(interval '30 days');$cron$
  );
end;
$$;